#!/bin/bash
[ ! -d "$(pwd)/vars" ] && mkdir vars
if type ip > /dev/null 2>&1; then
  ADDRS=$(ip addr|grep 'inet '|grep -v '\.1/'|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
else 
  ADDRS=$(ifconfig|grep 'inet '|grep -v '\.1 '|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
fi
if [ -f "$(pwd)/spec.yaml" ]; then
  echo "Using spec file: $(pwd)/spec.yaml"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -v $(pwd)/spec.yaml:/home/spec.yaml   -v $(pwd)/scripts/mainfuncs.sh:/home/scripts/mainfuncs.sh \
  -v $(pwd)/playbooks:/home/playbooks  -v $(pwd)/chaincode:/home/chaincode  -v "$(pwd)/app:/home/app"  \
  -v $(pwd)/main.sh:/home/main.sh -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
else
  echo "Using default spec file"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -v $(pwd)/main.sh:/home/main.sh -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
fi
